Quary.New/Controllers/PermiteesController.cs
using System;
using System.Web.Mvc;
using DevExpress.Web.Mvc;
using Models;
using Models.Repository;

namespace Quary.New.Controllers
{
    [Authorize]
    public class PermiteesController : Controller
    {
        // GET: Permitees
        private UnitOfWork unitOfWork = new UnitOfWork();
        public ActionResult Index()
        {
            return View();
        }

        [ValidateInput(false)]
        public ActionResult PermiteeGridViewPartial()
        {
            var model = unitOfWork.PermiteesRepo.Get();
            return PartialView("_PermiteeGridViewPartial", model);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult PermiteeGridViewPartialAddNew([ModelBinder(typeof(DevExpressEditorsBinder))] Permitees item)
        {
            //var model = new object[0];
            if (ModelState.IsValid)
            {
                try
                {
                    // Insert here a code to insert the new item in your model
                    unitOfWork.PermiteesRepo.Insert(item);
                    unitOfWork.Save();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            var model = unitOfWork.PermiteesRepo.Get();
            return PartialView("_PermiteeGridViewPartial", model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult PermiteeGridViewPartialUpdate([ModelBinder(typeof(DevExpressEditorsBinder))] Permitees item)
        {
            //var model = new object[0];
            if (ModelState.IsValid)
            {
                try
                {
                    // Insert here a code to update the item in your model
                    unitOfWork.PermiteesRepo.Update(item);
                    unitOfWork.Save();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            var model = unitOfWork.PermiteesRepo.Get();
            return PartialView("_PermiteeGridViewPartial", model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult PermiteeGridViewPartialDelete([ModelBinder(typeof(DevExpressEditorsBinder))] System.Int32 Id)
        {
           // var model = new object[0];
            if (Id >= 0)
            {
                try
                {
                    // Insert here a code to delete the item from your model
                    unitOfWork.PermiteesRepo.Delete(m => m.Id == Id);
                    unitOfWork.Save();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            var model = unitOfWork.PermiteesRepo.Get();
            return PartialView("_PermiteeGridViewPartial", model);
        }
    }
}

Quary.New/Controllers/ProgramOfWorksController.cs
using DevExpress.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Helpers;
using Models;
using Models.Repository;
using Microsoft.AspNet.Identity;

namespace Quary.New.Controllers
{
    public class ProgramOfWorksController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        public ActionResult AddEditProjectOfWorkPartial([ModelBinder(typeof(DevExpressEditorsBinder))]int? summaryId)
        {
            var model = unitOfWork.SummaryProgramOfWorksRepo.Find(m => m.Id == summaryId);
            return PartialView(model);
        }
        // GET: ProgramOfWorks
        [OnUserAuthorization(ActionName = "program of works")]
        public ActionResult Index()
        {
            return View();
        }

        [ValidateInput(false)]
        public ActionResult SummaryProgramOfWorkGridViewPartial([ModelBinder(typeof(DevExpressEditorsBinder))]int? programOfWorkId)
        {
            var model = unitOfWork.SummaryProgramOfWorksRepo.Get(m => m.ProgramOfWorkId == programOfWorkId);
            ViewBag.ProgramOfWorkId = programOfWorkId;
            return PartialView("_SummaryProgramOfWorkGridViewPartial", model);
        }

        [HttpPost, ValidateInput(false)]
        [OnUserAuthorization(ActionName = "add program of works")]
        public ActionResult SummaryProgramOfWorkGridViewPartialAddNew([ModelBinder(typeof(DevExpressEditorsBinder))] Models.SummaryProgramOfWorks item, [ModelBinder(typeof(DevExpressEditorsBinder))]int? programOfWorkId)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Insert here a code to insert the new item in your model
                    unitOfWork.SummaryProgramOfWorksRepo.Insert(item);
                    unitOfWork.Save();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            ViewBag.ProgramOfWorkId = programOfWorkId;
            var model = unitOfWork.SummaryProgramOfWorksRepo.Get(m => m.ProgramOfWorkId == programOfWorkId, includeProperties: "Sags,Particulars");
            return PartialView("_SummaryProgramOfWorkGridViewPartial", model);
        }
        [HttpPost, ValidateInput(false)]
        [OnUserAuthorization(ActionName = "update program of works")]
        public ActionResult SummaryProgramOfWorkGridViewPartialUpdate([ModelBinder(typeof(DevExpressEditorsBinder))] Models.SummaryProgramOfWorks item, [ModelBinder(typeof(DevExpressEditorsBinder))]int? programOfWorkId)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    unitOfWork.SummaryProgramOfWorksRepo.Update(item);
                    unitOfWork.Save();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            ViewBag.ProgramOfWorkId = programOfWorkId;
            var model = unitOfWork.SummaryProgramOfWorksRepo.Get(m => m.ProgramOfWorkId == programOfWorkId, includeProperties: "Sags,Particulars");
            return PartialView("_SummaryProgramOfWorkGridViewPartial", model);
        }
        [HttpPost, ValidateInput(false)]
        [OnUserAuthorization(ActionName = "delete program of works")]
        public ActionResult SummaryProgramOfWorkGridViewPartialDelete([ModelBinder(typeof(DevExpressEditorsBinder))]int? Id, [ModelBinder(typeof(DevExpressEditorsBinder))]int? programOfWorkId)
        {
            if (Id >= 0)
            {
                try
                {
                    // Insert here a code to delete the item from your model
                    unitOfWork.SummaryProgramOfWorksRepo.Delete(m => m.Id == Id);
                    unitOfWork.Save();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            ViewBag.ProgramOfWorkId = programOfWorkId;
            var model = unitOfWork.SummaryProgramOfWorksRepo.Get(m => m.ProgramOfWorkId == programOfWorkId, includeProperties: "Sags,Particulars");
            return PartialView("_SummaryProgramOfWorkGridViewPartial", model);
        }

        public ActionResult PrintPopupSummaryOfProgramOfWork([ModelBinder(typeof(DevExpressEditorsBinder))]int? programOfWorkId)
        {
            var programOfWorks = unitOfWork.ProgramOfWorksRepo.Find(m => m.Id == programOfWorkId);
            programOfWorks.SummaryProgramOfWorks.Clear();
            var item = new List<ProgramOfWorks>();
            var summary = new List<ReportSummaryProgramOfWorks>();
            var x = unitOfWork.SummaryProgramOfWorksRepo.Fetch(m => m.ProgramOfWorkId == programOfWorkId).ToList();
            foreach (var i in unitOfWork.SummaryProgramOfWorksRepo.Fetch(m => m.ProgramOfWorkId == programOfWorkId).GroupBy(m => m.ParticularId))
            {

                var r = new ReportSummaryProgramOfWorks()
                {
                    Amount = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key && m.ProgramOfWorks.Permitees.PermiteeTypes?.PermiteeTypeName != "Government Gratuitous").Sum(m => m.Amount),
                    OrdinaryEarth = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key).Sum(m => m.OrdinaryEarth),
                    OrdinaryAmount = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key && m.ProgramOfWorks.Permitees.PermiteeTypes?.PermiteeTypeName != "Government Gratuitous").Sum(m => m.OrdinaryAmount),
                    Mixed = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key).Sum(m => m.Mixed),
                    MixedAmount = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key && m.ProgramOfWorks.Permitees.PermiteeTypes?.PermiteeTypeName != "Government Gratuitous").Sum(m => m.MixedAmount),
                    Boulders = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key).Sum(m => m.Boulders),
                    BouldersAmount = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key && m.ProgramOfWorks.Permitees.PermiteeTypes?.PermiteeTypeName != "Government Gratuitous").Sum(m => m.BouldersAmount),
                    Coarse = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key).Sum(m => m.Coarse),
                    CoarseAmount = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key && m.ProgramOfWorks.Permitees.PermiteeTypes?.PermiteeTypeName != "Government Gratuitous").Sum(m => m.CoarseAmount),
                    CrushedRocks = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key ).Sum(m => m.CrushedRocks),
                    CrushedRocksAmount = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key && m.ProgramOfWorks.Permitees.PermiteeTypes?.PermiteeTypeName != "Government Gratuitous").Sum(m => m.CrushedRocksAmount),
                    FineScreen = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key).Sum(m => m.FineScreen),
                    FineScreenAmount = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key && m.ProgramOfWorks.Permitees.PermiteeTypes?.PermiteeTypeName != "Government Gratuitous").Sum(m => m.FineScreenAmount),

                    Total = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key).Sum(m => m.Total),
                    TotalAmount = x.Where(m => m.ProgramOfWorkId == programOfWorkId && m.ParticularId == i.Key && m.ProgramOfWorks.Permitees.PermiteeTypes?.PermiteeTypeName != "Government Gratuitous").Sum(m => m.TotalAmount),
                    Particulars = unitOfWork.ParticularsRepo.Find(m => m.Id == i.Key),
                    Permittee = x.FirstOrDefault(m => m.ProgramOfWorkId == programOfWorkId)?.ProgramOfWorks?.Permitees
                };
                summary.Add(r);
            }




            programOfWorks.ReportSummaryProgramOfWorks = summary;
            item.Add(programOfWorks);
            rptSummaryProgramOfWorks report = new rptSummaryProgramOfWorks()
            {
                DataSource = item
            };
            var userId = User.Identity.GetUserId();
            var user = unitOfWork.UsersRepo.Find(m => m.Id == userId);
            report.lblPreparedBy.Text = user?.FullName?.ToUpper();
            report.lblPosition.Text = user?.Position?.ToUpper();
            return PartialView(report);
        }
    }
}

Quary.New/Views/FileManagement/AddEditParticularPartial.cshtml
@model Particulars
<div class="row">
    <div class="col-md-12 col-lg-12">
        @{
            Html.DevExpress().TextBoxFor(m => m.Particular, settings =>
            {
                settings.Properties.NullText = "Particular";
                settings.Width = Unit.Percentage(100);
                settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Left;
                settings.Properties.Caption = "Particular";
                settings.ShowModelErrors = true;
                settings.Properties.ValidationSettings.Display = Display.Dynamic;
            }).GetHtml();
        }
    </div>

</div>
<div class="row margin-top-10">
    <div class="col-lg-12 col-md-12 ">
        @{
            Html.DevExpress().Button(settings =>
            {
                settings.Name = "btnSubmit";
                settings.Text = "Submit";
                settings.ClientSideEvents.Click = "function(s,e){ParticularGridView.UpdateEdit()}";
            }).GetHtml();
            Html.DevExpress().Button(settings =>
            {
                settings.Name = "btnCancel";
                settings.Text = "Cancel";
                settings.ControlStyle.CssClass = "margin-left-10";
                settings.ClientSideEvents.Click = "function(s,e){ParticularGridView.CancelEdit()}";
            }).GetHtml();
        }
    </div>
</div>

Quary.New/Views/FileManagement/AddEditProgramOfWorkPartial.cshtml
@model ProgramOfWorks
<div class="row">
    <div class="col-md-12 col-lg-12">
        @{
            Html.DevExpress().ComboBoxFor(m => m.PermitteeId, settings =>
            {
                settings.Properties.NullText = "Permittee";
                settings.Width = Unit.Percentage(100);
                settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Left;
                settings.Properties.Caption = "Permittee";
                settings.ShowModelErrors = true;
                settings.Properties.ValidationSettings.Display = Display.Dynamic;
                settings.Properties.TextField = "CompanyName";
                settings.Properties.ValueField = "Id";
            }).BindList(new UnitOfWork().PermiteesRepo.Get()).GetHtml();
        }
    </div>

</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        @{
            Html.DevExpress().TextBoxFor(m => m.Name, settings =>
            {
                settings.Properties.NullText = "Program of Work Name";
                settings.Width = Unit.Percentage(100);
                settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Left;
                settings.Properties.Caption = "Program of Work Name";
                settings.ShowModelErrors = true;
                settings.Properties.ValidationSettings.Display = Display.Dynamic;
            }).GetHtml();
        }
    </div>

</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        @{
            Html.DevExpress().TextBoxFor(m => m.Address, settings =>
            {
                settings.Properties.NullText = "Address";
                settings.Width = Unit.Percentage(100);
                settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Left;
                settings.Properties.Caption = "Address";
         
                settings.ShowModelErrors = true;
                
                settings.Properties.ValidationSettings.Display = Display.Dynamic;
            }).GetHtml();
        }
    </div>

</div>

<div class="row">
    <div class="col-md-12 col-lg-12">
        @{
            Html.DevExpress().TextBoxFor(m => m.Cost, settings =>
            {
                settings.Properties.NullText = "Cost";
                settings.Width = Unit.Percentage(100);
                settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Left;
                settings.Properties.Caption = "Cost";

                settings.ShowModelErrors = true;

                settings.Properties.ValidationSettings.Display = Display.Dynamic;
            }).GetHtml();
        }
    </div>

</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        @{
            Html.DevExpress().TextBoxFor(m => m.FilingDate, settings =>
            {
                settings.Properties.NullText = "Filing Date";
                settings.Width = Unit.Percentage(100);
                settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Left;
                settings.Properties.Caption = "Filing Date";

                settings.ShowModelErrors = true;

                settings.Properties.ValidationSettings.Display = Display.Dynamic;
            }).GetHtml();
        }
    </div>

</div>


<div class="row">
    <div class="col-md-12 col-lg-12">
        @{
            Html.DevExpress().TextBoxFor(m => m.SourceFund, settings =>
            {
                settings.Properties.NullText = "Source Fund";
                settings.Width = Unit.Percentage(100);
                settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Left;
                settings.Properties.Caption = "Source Fund";

                settings.ShowModelErrors = true;

                settings.Properties.ValidationSettings.Display = Display.Dynamic;
            }).GetHtml();
        }
    </div>

</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        @{
            Html.DevExpress().DateEditFor(m => m.DateStarted, settings =>
            {
                settings.Properties.NullText = "Date Started";
                settings.Width = Unit.Percentage(100);
                settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Left;
                settings.Properties.Caption = "Date Started";

                settings.ShowModelErrors = true;

                settings.Properties.ValidationSettings.Display = Display.Dynamic;
            }).GetHtml();
        }
    </div>

</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        @{
            Html.DevExpress().DateEditFor(m => m.DateFinish, settings =>
            {
                settings.Properties.NullText = "Date Finish";
                settings.Width = Unit.Percentage(100);
                settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Left;
                settings.Properties.Caption = "Date Finish";

                settings.ShowModelErrors = true;

                settings.Properties.ValidationSettings.Display = Display.Dynamic;
            }).GetHtml();
        }
    </div>

</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        @{
            Html.DevExpress().TextBoxFor(m => m.Proponent, settings =>
            {
                settings.Properties.NullText = "Proponent";
                settings.Width = Unit.Percentage(100);
                settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Left;
                settings.Properties.Caption = "Proponent";

                settings.ShowModelErrors = true;

                settings.Properties.ValidationSettings.Display = Display.Dynamic;
            }).GetHtml();
        }
    </div>

</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        @{

        }
    </div>

</div>

<div class="row margin-top-10">
    <div class="col-lg-12 col-md-12 ">
        @{
            Html.DevExpress().Button(settings =>
            {
                settings.Name = "btnSubmit";
                settings.Text = "Submit";
                settings.ClientSideEvents.Click = "function(s,e){ProgramOfWorkGridView.UpdateEdit()}";

            }).GetHtml();
            Html.DevExpress().Button(settings =>
            {
                settings.Name = "btnCancel";
                settings.Text = "Cancel";
                settings.ControlStyle.CssClass = "margin-left-10";
                settings.ClientSideEvents.Click = "function(s,e){ProgramOfWorkGridView.CancelEdit()}";
            }).GetHtml();
        }
    </div>
</div>

Quary.New/Views/FileManagement/Categories.cshtml
@{
    ViewBag.Title = "Categories";
    Layout = "~/Views/Shared/_layout.cshtml";
}


@Html.Action("CategoryGridViewPartial")

Quary.New/Views/FileManagement/Facilities.cshtml
@{
    ViewBag.Title = "Facilities";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@Html.Action("FacilitiesGridViewPartial")

Quary.New/Views/FileManagement/PermiteeTypes.cshtml
@{
    ViewBag.Title = "Permitee Types";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@Html.Action("PermiteeTypeGridViewPartial")

Quary.New/Views/FileManagement/ProgramOfWorks.cshtml
@{
    ViewBag.Title = "Program Of Works";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form>

    @Html.Action("ProgramOfWorkGridViewPartial")
</form>
<div id="print-container">

</div>
<script>
    function changeProgramofWork(s) {
        $('form').submit();
        if (s.GetValue() != null)
            btnPrint.SetEnabled(true);
    }
    function PrintProgramOfWork(Id) {

        showLoading();
        $.ajax({
            url: '@Url.Action("PrintPopupSummaryOfProgramOfWork","ProgramOfWorks")',
            data: { ProgramOfWorkId: Id },
            success: function (s) {
                $('#print-container').html(s);
                hideLoading();
            }
        });
    }

    function InputPrepared() {

        showLoading();
        $.ajax({
            url: '@Url.Action("PrintPopupSummaryOfProgramOfWork", "ProgramOfWorks")',
            data: { ProgramOfWorkId: ProgramOfWorkId.GetValue() },
            success: function (s) {
                $('#print-container').html(s);
                hideLoading();
            }
        });
    }
    function NewButton(s, e) {
        if (e.buttonIndex == 0)
            window.location.href = '@Url.Action("ProgramOfWorks","Filemanagement")';
    }
</script>

Quary.New/Views/FileManagement/Quarries.cshtml
@{
    ViewBag.Title = "Quarries";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@Html.Action("QuarriesGridViewPartial")

Quary.New/Views/FileManagement/TransactionItems.cshtml
@{
    ViewBag.Title = "Transaction Items";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@Html.Action("TransactionItemsGridViewPartial")

Quary.New/Views/FileManagement/_FacilitiesGridViewPartial.cshtml
@{
    var grid = Html.DevExpress().GridView(settings =>
    {
        settings.Name = "FacilitiesGridView";
        settings.Width = Unit.Percentage(100);
        settings.CallbackRouteValues = new { Controller = "FileManagement", Action = "FacilitiesGridViewPartial" };

        settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "FileManagement", Action = "FacilitiesGridViewPartialAddNew" };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "FileManagement", Action = "FacilitiesGridViewPartialUpdate" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "FileManagement", Action = "FacilitiesGridViewPartialDelete" };
        settings.SettingsEditing.Mode = GridViewEditingMode.EditFormAndDisplayRow;
        settings.SettingsBehavior.ConfirmDelete = true;

        settings.CommandColumn.Visible = true;
        settings.CommandColumn.ShowNewButtonInHeader = true;
        settings.CommandColumn.ShowDeleteButton = true;
        settings.CommandColumn.ShowEditButton = true;

        settings.KeyFieldName = "Id";

        settings.SettingsPager.Visible = true;
        settings.Settings.ShowGroupPanel = false;
        settings.Settings.ShowFilterRow = false;
        settings.SettingsBehavior.AllowSelectByRowClick = true;

        settings.SettingsAdaptivity.AdaptivityMode = GridViewAdaptivityMode.HideDataCells;
        settings.SettingsAdaptivity.AdaptiveColumnPosition = GridViewAdaptiveColumnPosition.Right;
        settings.SettingsAdaptivity.AdaptiveDetailColumnCount = 1;
        settings.SettingsAdaptivity.AllowOnlyOneAdaptiveDetailExpanded = true;
        settings.SettingsAdaptivity.HideDataCellsAtWindowInnerWidth = 300;

        settings.AddAddEditDeleteToolbar();


        settings.Columns.Add("FacilityName");
        settings.Columns.Add(col =>
        {
            col.FieldName = "Cost";
            col.ColumnType = MVCxGridViewColumnType.TextBox;
            col.PropertiesEdit.DisplayFormatString = "N2";
        });
        settings.SetEditFormTemplateContent(col =>
        {
            Html.DevExpress().PopupControl(pop =>
            {
                pop.HeaderText = DataBinder.Eval(col.DataItem, "FacilityName")?.ToString()?? "Facility Name";
                pop.Width = Unit.Pixel(700);
                pop.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
                pop.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
                pop.Name = col.KeyValue+"_popup";
                pop.Modal = true;
                pop.ShowOnPageLoad = true;
                pop.CloseOnEscape = false;
                pop.ShowCloseButton = true;
                pop.ClientSideEvents.CloseUp = "function(s,e){FacilitiesGridView.CancelEdit()}";
                pop.CloseAction = CloseAction.CloseButton;
                pop.SetContent(() =>
                {
                    if (ViewData["EditError"] != null && ViewData["Model"] != null)
                    {
                        Html.RenderPartial("AddEditFacilitiesPartial", ViewData["Model"]);
                    }
                    else
                    {
                        Html.RenderAction("AddEditFacilitiesPartial", new { facilitiesId = col.KeyValue });
                    }
                });
            }).GetHtml();




        });

    });
    if (ViewData["EditError"] != null)
    {
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()

Quary.New/Views/FileManagement/_TransactionTypeGridViewPartial.cshtml
@{
	var grid = Html.DevExpress().GridView(settings =>
	{
	    settings.Width = Unit.Percentage(100);
        settings.Name = "TransactionTypeGridView";
        settings.CallbackRouteValues = new { Controller = "FileManagement", Action = "TransactionTypeGridViewPartial" };

				settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "FileManagement", Action = "TransactionTypeGridViewPartialAddNew" };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "FileManagement", Action = "TransactionTypeGridViewPartialUpdate" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "FileManagement", Action = "TransactionTypeGridViewPartialDelete" };
	    settings.SettingsEditing.Mode = GridViewEditingMode.EditFormAndDisplayRow;
        settings.SettingsBehavior.ConfirmDelete = true;

		settings.CommandColumn.Visible = true;
        settings.CommandColumn.ShowNewButton = true;
        settings.CommandColumn.ShowDeleteButton = true;
        settings.CommandColumn.ShowEditButton = true;
	                                                      settings.AddAddEditDeleteToolbar();
		settings.KeyFieldName = "Id";

		settings.SettingsPager.Visible = true;
		settings.Settings.ShowGroupPanel = false;
		settings.Settings.ShowFilterRow = true;
		settings.SettingsBehavior.AllowSelectByRowClick = true;

		settings.SettingsAdaptivity.AdaptivityMode = GridViewAdaptivityMode.HideDataCells;
		settings.SettingsAdaptivity.AdaptiveColumnPosition = GridViewAdaptiveColumnPosition.Right;
		settings.SettingsAdaptivity.AdaptiveDetailColumnCount = 1;
		settings.SettingsAdaptivity.AllowOnlyOneAdaptiveDetailExpanded = true;
		settings.SettingsAdaptivity.HideDataCellsAtWindowInnerWidth = 0;
        
				settings.Columns.Add("TransactionType");
			});
		if (ViewData["EditError"] != null){
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()